#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <assert.h>
#include <stdbool.h>
#include "root_table.h"
#include "automaton_graph.h"
#include "file_input_output_matrix.h"
#include "cox_grp_limits.h"
#include "user_input.h"
#include "cox_action.h"
#include "automaton_binary_tree.h"
#include "string_stack.h"
#include "main.h"
